# motif = "commonly shared interval of DNA between 2 different organisms' genome"
# position of a symbol i in string s = total number of symbols found to its left, including itself; denoted s[i]
# location of a substring s[j:k] = its beginning position j

# Given: 2 DNA strings s and t
# Return: All locations of t as a substring of s

import re

pos_lst = []

q = 'GATATATGCATATACTT'
p = 'ATAT'

t = 'GTGGTGTTGCCGTGGTGTGTGGTGTCTACGGTGGTGTAGTGGTGTGGTGGTGTAACTTGAGTGGTGTTTGTGGTGTGTGGTGTTTCGGGGGGTGGTGTGTGGTGTGTGGTGTGTGGTGTTGTGGTGTCTCTAGGTGGTGTGTGGTGTATCGTATGTGGTGTGTGGTGTGTGGTGTTGCGGTGGTGTACGTGGTGTAGTGGTGTTGTGGTGTTCGTGGTGTCTAGTGGTGTGCGTGGTGTTGTGGTGGTGTAAATTGTGGTGTAGTGGTGTCCGCGACTACAGTGGTGTTAGTGGTGTGTGTGGTGTGTGGTGTGCGGAAGTGGTGTGTGGTGTGTGGTGTGTGGTGTCGTGGTGTAAGTGGTGTTGTGGTGTGGTGGTGTTGTGGTGTGGGGTGGTGTGTGGTGTGGTCGTGGTGTGTCATATGTGGTGTACTTGTGGTGTGTGGTGTTATGTGGTGTGAGCTGTGGTGTGTGAGTGGTGTGTGGTGTCGTGGTGTAGTGGTGTGTGGTGTGGTGGTGTGGTGGTGTCCACTCGTGGTGTGGTGGTGTAGCGTGTAGGCGGCAGTGGTGTCACAAGGTGGTGTAGAAGTGGTGTGGAGTGGTGTGTGGTGTCAAATCGTGGTGTCGCGTGGTGTGTGGTGTTGTAGTGGTGTGTGGTGTGATTAGGTGGTGTTTTGCCGTGGTGTGTGGTGTGTATTTTGTGGTGTCACGTATGTGGTGTCGAGAGGTGGTGTGTGGTGTGGTGGTGTGGTGGTGTGTGGTGTGTGGTGTATGGTGGTGTACGGACGTGGTGTCAGCACCGGTGGTGTCGTGGTGTGTAGGTGGTGTTTATGGCAGTCCACGTGGTGTGCATGCGTGGTGTGTGGTGTACGCATGAGGCTATGCGTGGTGTCAAGTGGTGTAGTAGGTGGTGTGGTGGTGTATGTGGTGTGTGGTGT'
s = 'GTGGTGTGT'

for match in re.finditer(rf"(?={re.escape(s)})", t):
    pos_lst.append(match.start() + 1)
    start = match.start()
    end = match.start() + len(s)
    if t[match.start():end] == y:
        print(f"{t[start:end]}: {start}, {end}")

print(pos_lst)
print(len(pos_lst))
